# @generated by `metor-fsw stubgen` from the `demo` pack manifest (crate `demo-systems`).
# Do not edit by hand.
#
# Regenerate after changing the pack's params or ports:
#     metor-fsw stubgen
# Verify the checked-in stubs are current (CI):
#     metor-fsw stubgen --check
"""Typed pack module for artifact `demo`."""

from __future__ import annotations

from metor_config import Artifact, Frame, InPort, Msg, OutPort, System

ARTIFACT = Artifact(
    id="demo",
    crate="demo-systems",
    lib="demo_systems",
    manifest_hash="sha256:4799f397f889dbd68ee56b1b95fd5dc212b87f1e7a0684a69797f430a8806f74",
)


class Cmd(Frame):
    """Frame marker (checker-only)."""


class Sensors(Frame):
    """Frame marker (checker-only)."""


class ModeCmd(Frame):
    """Frame marker (checker-only)."""


class Widget(System):
    """`Widget` pack entry.

    Parameters:
        count: How many widgets to make.
        gain: Loop gain (1/s), ~3e-12 at 400 km.
    """

    def __init__(
        self,
        *,
        count: int = 0,
        gain: float = 0.0,
        label: str = "",
        armed: bool = False,
        limit: int | None = None,
        offsets: tuple[float, float, float] = (0.0, 0.0, 0.0),
    ) -> None:
        super().__init__(
            "Widget",
            ARTIFACT,
            count=count,
            gain=gain,
            label=label,
            armed=armed,
            limit=limit,
            offsets=offsets,
        )

    cmd: InPort[Cmd]  # input, latest-wins
    sensors: OutPort[Sensors]  # output, latest-wins, telemetered
    events: OutPort[Msg]  # output, log


def startup() -> System:
    """Occupant `startup` for a `mode`-style slot's allow set."""
    return System("startup", ARTIFACT)
