# @generated by `metor-fsw pack dev` from the `demo` pack manifest (crate `demo-systems`).
# Do not edit by hand.
#
# Regenerate after changing the pack's params or ports:
#     metor-fsw pack dev
# (a `uv sync` of a target depending on this pack runs it for you)
"""Typed pack module for artifact `demo`."""

from __future__ import annotations

from pathlib import Path

from dataclasses import dataclass
from typing import Literal, Sequence

from metor_config import Artifact, Frame, InPort, Msg, OutPort, System

ARTIFACT = Artifact(
    id="demo",
    crate="demo-systems",
    lib="demo_systems",
    manifest_hash="sha256:19754293a68b18f45aa4ff7b534df3f99b4950ff93afe9a9b8958f4911a3288e",
    prebuilt=str(Path(__file__).resolve().parent / "_libs"),
    abi_version=12,
    dist="demo-pack",
    dist_version="1.2.0",
)


class Cmd(Frame):
    """Frame marker (checker-only)."""


class Sensors(Frame):
    """Frame marker (checker-only)."""


class SystemStatus(Frame):
    """Frame marker (checker-only)."""


class ModeCmd(Frame):
    """Frame marker (checker-only)."""


class Widget(System):
    """`Widget` pack entry.

    Parameters:
        count: How many widgets to make.
        gain: Loop gain (1/s), ~3e-12 at 400 km.
    """

    def __init__(
        self,
        *,
        count: int = 0,
        gain: float = 0.0,
        label: str = "",
        armed: bool = False,
        limit: int | None = None,
        offsets: tuple[float, float, float] = (0.0, 0.0, 0.0),
    ) -> None:
        super().__init__(
            "Widget",
            ARTIFACT,
            count=count,
            gain=gain,
            label=label,
            armed=armed,
            limit=limit,
            offsets=offsets,
        )

    cmd: InPort[Cmd]  # input, latest-wins
    sensors: OutPort[Sensors]  # output, latest-wins, telemetered
    events: OutPort[Msg]  # output, log
    system_status: OutPort[SystemStatus]  # output, latest-wins, telemetered, host-written


def startup() -> System:
    """Occupant `startup` for a `mode`-style slot's allow set."""
    return System("startup", ARTIFACT)
