//! Offline, exact endpoint contracts for peer telemetry.
//!
//! Contracts describe channels independently of graph instance names and network
//! addresses. They can be generated by a contract crate and exchanged as JSON
//! without loading a remote system. This module performs contract comparison;
//! it neither connects sockets nor validates incoming frame records.

mod layout;
mod validate;

pub use layout::{ByteOrder, DynamicBounds, DynamicField, FieldLayout, FrameLayout};

use std::collections::BTreeMap;

use metor_proto::types::ComponentId;
use metor_proto::vtable::VTable;
use metor_proto_wkt::ComponentMetadata;
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};

use crate::{Delivery, Frame, PortDesc, PortSchema};

/// Version of both the manifest shape and its canonical JSON hash rules.
pub const CONTRACT_VERSION: u32 = 1;
/// Bound parsing before allocating a JSON value tree. Transport must also
/// enforce a length bound before reading a manifest off the wire.
pub const MAX_CONTRACT_BYTES: usize = 1 << 20;
pub const MAX_CHANNELS: usize = 256;

/// One named publication interface. `version` is the application's ICD version;
/// `format_version` versions this library's manifest representation.
#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct EndpointContract {
    pub format_version: u32,
    pub name: String,
    pub version: String,
    /// Identifies the interpretation/epoch of source timestamps. Naming a clock
    /// domain does not synchronize clocks or make receive-age subtraction safe.
    pub clock_domain: String,
    #[serde(default)]
    pub description: String,
    pub channels: Vec<FrameChannel>,
}

/// A channel key is distinct from its frame type ID. Two sensors of the same
/// type may occupy distinct channels without renaming either Rust frame.
#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct FrameChannel {
    pub key: String,
    pub delivery: Delivery,
    pub frame: FrameSchema,
    /// Contractual units, coordinate conventions, etc., keyed by field path or
    /// convention name. Every entry affects compatibility.
    #[serde(default)]
    pub semantics: BTreeMap<String, String>,
    #[serde(default)]
    pub description: String,
}

/// Native frame bytes plus the complete unprefixed telemetry schema.
#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct FrameSchema {
    pub name: String,
    pub frame_id: ComponentId,
    pub byte_order: ByteOrder,
    pub layout: FrameLayout,
    pub max_record_size: u64,
    pub vtable: VTable,
    pub metadata: Vec<ComponentMetadata>,
}

/// A contract failure names the channel/property that needs attention.
#[derive(Debug, thiserror::Error)]
pub enum ContractError {
    #[error("invalid peer contract at {path}: {reason}")]
    Invalid { path: String, reason: String },
    #[error("peer contract mismatch at {path}: expected {expected}, received {actual}")]
    Mismatch {
        path: String,
        expected: String,
        actual: String,
    },
    #[error("peer contract JSON: {0}")]
    Json(#[from] serde_json::Error),
}

impl ContractError {
    fn invalid(path: impl Into<String>, reason: impl Into<String>) -> Self {
        Self::Invalid {
            path: path.into(),
            reason: reason.into(),
        }
    }
}

impl FrameChannel {
    /// Describe a local type. Missing layout metadata and unsupported nested
    /// dynamics are errors rather than weaker contracts.
    pub fn of<F: Frame>(key: impl Into<String>, delivery: Delivery) -> Result<Self, ContractError> {
        let PortSchema::Table {
            frame_id,
            vtable,
            metadata,
        } = PortDesc::of::<F>().schema
        else {
            unreachable!("Frame ports always have table schema")
        };
        let layout = F::peer_layout().ok_or_else(|| {
            ContractError::invalid(
                F::NAME,
                "Frame implementation does not export peer layout metadata",
            )
        })?;
        let channel = Self {
            key: key.into(),
            delivery,
            frame: FrameSchema {
                name: F::NAME.into(),
                frame_id,
                byte_order: ByteOrder::NATIVE,
                layout,
                max_record_size: F::MAX_SIZE as u64,
                vtable,
                metadata,
            },
            semantics: BTreeMap::new(),
            description: String::new(),
        };
        channel.validate()?;
        Ok(channel)
    }

    /// Check the exact schema/layout of a local binding. This checks the frame
    /// type only; the target must separately match delivery and semantics.
    pub fn require_frame<F: Frame>(&self) -> Result<(), ContractError> {
        self.validate()?;
        let local = Self::of::<F>(&self.key, self.delivery)?;
        compare(
            &format!("channels.{}.frame", self.key),
            &schema_value(&self.frame)?,
            &schema_value(&local.frame)?,
        )
    }
}

impl EndpointContract {
    pub fn new(
        name: impl Into<String>,
        version: impl Into<String>,
        clock_domain: impl Into<String>,
        channels: Vec<FrameChannel>,
    ) -> Result<Self, ContractError> {
        let this = Self {
            format_version: CONTRACT_VERSION,
            name: name.into(),
            version: version.into(),
            clock_domain: clock_domain.into(),
            description: String::new(),
            channels,
        };
        this.validate()?;
        Ok(this)
    }

    /// Parse and validate a data-only manifest, without a network connection.
    pub fn from_json(json: &str) -> Result<Self, ContractError> {
        if json.len() > MAX_CONTRACT_BYTES {
            return Err(ContractError::invalid("manifest", "exceeds 1 MiB limit"));
        }
        let this: Self = serde_json::from_str(json)?;
        this.validate()?;
        Ok(this)
    }

    /// Export deterministic JSON, retaining descriptions for human readers.
    pub fn to_json(&self) -> Result<String, ContractError> {
        let value = self.value(false)?;
        let json = serde_json::to_string_pretty(&value)?;
        if json.len() > MAX_CONTRACT_BYTES {
            return Err(ContractError::invalid("manifest", "exceeds 1 MiB limit"));
        }
        Ok(json)
    }

    /// Canonical compact UTF-8 JSON: object keys sorted recursively, channels
    /// sorted by key, component metadata sorted by ID/name, and descriptions
    /// excluded. Vtable arrays retain their exact order, including op references.
    /// Component metadata and explicit semantics are contractual in their entirety.
    pub fn canonical_bytes(&self) -> Result<Vec<u8>, ContractError> {
        let bytes = serde_json::to_vec(&self.value(true)?)?;
        if bytes.len() > MAX_CONTRACT_BYTES {
            return Err(ContractError::invalid("manifest", "exceeds 1 MiB limit"));
        }
        Ok(bytes)
    }

    /// SHA-256 of the versioned canonical manifest, suitable for pinning an ICD.
    pub fn hash(&self) -> Result<String, ContractError> {
        let digest = Sha256::digest(self.canonical_bytes()?);
        Ok(format!("sha256:{digest:x}"))
    }

    /// Exact match with a property-level diagnostic. Never falls back to the
    /// more permissive local component-subset compatibility rule.
    pub fn require_exact(&self, received: &Self) -> Result<(), ContractError> {
        compare("contract", &self.value(true)?, &received.value(true)?)
    }

    fn value(&self, omit_descriptions: bool) -> Result<serde_json::Value, ContractError> {
        self.validate()?;
        let mut this = self.clone();
        this.channels.sort_by(|a, b| a.key.cmp(&b.key));
        for channel in &mut this.channels {
            sort_metadata(&mut channel.frame);
        }
        let mut value = serde_json::to_value(this)?;
        if omit_descriptions {
            value.as_object_mut().unwrap().remove("description");
            for channel in value["channels"].as_array_mut().unwrap() {
                channel.as_object_mut().unwrap().remove("description");
            }
        }
        sort_objects(&mut value);
        Ok(value)
    }
}

fn sort_metadata(frame: &mut FrameSchema) {
    frame
        .metadata
        .sort_by(|a, b| (a.component_id, &a.name).cmp(&(b.component_id, &b.name)));
}

fn schema_value(frame: &FrameSchema) -> Result<serde_json::Value, ContractError> {
    let mut frame = frame.clone();
    sort_metadata(&mut frame);
    let mut value = serde_json::to_value(frame)?;
    sort_objects(&mut value);
    Ok(value)
}

// Do not rely on serde_json's preserve_order feature being disabled by every
// workspace member. Explicit sorting also pins the exported JSON representation.
fn sort_objects(value: &mut serde_json::Value) {
    match value {
        serde_json::Value::Object(map) => {
            let sorted: BTreeMap<_, _> = std::mem::take(map).into_iter().collect();
            for (key, mut value) in sorted {
                sort_objects(&mut value);
                map.insert(key, value);
            }
        }
        serde_json::Value::Array(values) => values.iter_mut().for_each(sort_objects),
        _ => {}
    }
}

fn compare(
    path: &str,
    expected: &serde_json::Value,
    actual: &serde_json::Value,
) -> Result<(), ContractError> {
    if expected == actual {
        return Ok(());
    }
    match (expected, actual) {
        (serde_json::Value::Object(a), serde_json::Value::Object(b)) if a.keys().eq(b.keys()) => {
            for (key, value) in a {
                compare(&format!("{path}.{key}"), value, &b[key])?;
            }
        }
        (serde_json::Value::Array(a), serde_json::Value::Array(b)) if a.len() == b.len() => {
            for (index, (a, b)) in a.iter().zip(b).enumerate() {
                compare(&format!("{path}[{index}]"), a, b)?;
            }
        }
        _ => {}
    }
    Err(ContractError::Mismatch {
        path: path.into(),
        expected: expected.to_string(),
        actual: actual.to_string(),
    })
}

#[cfg(test)]
mod tests;
