//! A typed subset of Python, compiled to closed WebAssembly modules.
//!
//! The premise, from `metor-fsw-2/docs/plans/python-expressions.md`: the panel
//! and the vehicle should run *the same artifact*, an operator should write it
//! in the language they already write `target.py` in, and typing a character
//! into an expression field should not be able to stall anything. That rules
//! out shipping an interpreter as the guest (no static output schema, no
//! closed module, fuel that meters dispatch rather than user work) and it
//! rules out any pipeline with a toolchain in it. What is left is a compiler
//! small enough to live in the flight binary: parse, check, encode.
//!
//! This crate is Phase 0 of that — the compiler spike, no frames and no
//! decorators. What it establishes is the substrate the rest sits on.
//!
//! ```
//! let module = metor_expr::compile("def f(x: f64) -> f64:\n    return x * 2.0\n").unwrap();
//! assert_eq!(module.manifest.functions[0].name, "f");
//! ```
//!
//! ## Nothing links at compile time
//!
//! `wasm32-unknown-unknown` is needed to *regenerate* the prelude, never to
//! compile an expression. The prelude — `prelude/`, built by
//! `scripts/regen-prelude.sh` — is checked in as [`PRELUDE`], and compiling
//! means appending functions to those bytes: new types, new bodies, new
//! exports, new data, same memory. [`template`] carries that, including the
//! call-graph walk that drops kernels a program never reaches, so a module
//! that wanted `sin` does not also ship a matmul.
//!
//! Scalar arithmetic never enters the prelude at all. `a * b + c` is native
//! wasm opcodes; the prelude is entered for transcendentals, for tensor
//! kernels, and for nothing else.
//!
//! ## Tensors are addresses
//!
//! Every tensor in a compiled program lives at an address the compiler picked,
//! above the linker's `__heap_base`. That is what makes kernel call sites
//! constant — an elementwise operation is `i32.const desc; call $k_add`, where
//! `desc` is a data segment holding both operand addresses and all three
//! shapes — and it is why the guest needs no allocator. It also gives the
//! host ABI its shape: a function whose signature mentions a tensor takes no
//! wasm parameters, and is driven through `<name>_arg_ptr(i)`, `<name>()`,
//! `<name>_ret_ptr()`. See [`FnSig::uses_buffers`].
//!
//! ## The pipeline
//!
//! [`compile`] is three passes and no more. `rustpython-parser` produces a
//! Python AST; [`check`](mod@check) turns it into a typed IR, which is the
//! only representation of a program this crate keeps; [`codegen`](mod@codegen)
//! emits. The checker is the *single* validation gate — codegen re-derives
//! nothing and guards against nothing, because everything it could guard
//! against was already refused with a span.
//!
//! ## Numerics are nox's, and nox is the oracle
//!
//! The subset's semantics are a tensor library's, not CPython's: ints are
//! `i64` and wrap, `/` is always true division, `//` and `%` floor. Every
//! semantic test therefore runs twice — compiled, under fuel-metered wasmi,
//! and natively against nox in-process — and the results must agree. There is
//! no second interpreter in the loop. See `tests::differential` for the
//! harness and for the one place the oracle needed care.
//!
//! The M0 spike qualified nox's role in one place, by measurement. nox's
//! *fixed shape* path (`Tensor<f64, Const<N>, ArrayRepr>`) is correct and well
//! exercised, and it is the oracle. Its *dynamic* shape path is not: an
//! `Array<T, Dyn>` is `Vec`-backed so every operation allocates,
//! `RealField: faer::ComplexField` pulls faer's gemm into the guest, and
//! `DynArray::default` sizes buffers by the sum of the dims instead of their
//! product, so a `Dyn` 3×3 gets six elements. The guest therefore takes
//! `nox_array::ArrayView` — the shape-plus-slice view, which has no
//! dependencies beyond `zerocopy` — and writes its loops out by hand. See the
//! plan's Results section for the numbers behind that.

mod check;
mod codegen;
mod diag;
mod ir;
pub mod template;

pub use diag::{Diagnostic, Diagnostics, Span};

/// The guest template generated functions are appended to.
///
/// Regenerated by `scripts/regen-prelude.sh`, which is the only thing in this
/// crate that needs a wasm toolchain.
pub const PRELUDE: &[u8] = include_bytes!("prelude.wasm");

/// An element type. Only `f64` participates in tensors today; the rest of the
/// vocabulary is here because the manifest is what Phase 1 serializes.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Dtype {
    F64,
    I64,
    Bool,
}

/// A value's type in the subset.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum Ty {
    F64,
    I64,
    Bool,
    Tensor { dtype: Dtype, shape: Vec<usize> },
}

impl std::fmt::Display for Ty {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Ty::F64 => write!(f, "f64"),
            Ty::I64 => write!(f, "i64"),
            Ty::Bool => write!(f, "bool"),
            Ty::Tensor { dtype, shape } => {
                let dtype = match dtype {
                    Dtype::F64 => "f64",
                    Dtype::I64 => "i64",
                    Dtype::Bool => "bool",
                };
                match shape.as_slice() {
                    [n] => write!(f, "Tensor[{dtype}, {n}]"),
                    dims => {
                        write!(f, "Tensor[{dtype}, (")?;
                        for (i, d) in dims.iter().enumerate() {
                            if i > 0 {
                                write!(f, ", ")?;
                            }
                            write!(f, "{d}")?;
                        }
                        write!(f, ")]")
                    }
                }
            }
        }
    }
}

/// One exported function: what to call it and what it takes.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct FnSig {
    pub name: String,
    pub params: Vec<(String, Ty)>,
    pub ret: Ty,
}

impl FnSig {
    /// Whether this function crosses through static buffers rather than by
    /// value.
    ///
    /// A tensor anywhere in the signature moves the whole signature into
    /// memory: the host writes argument `i` at `<name>_arg_ptr(i)`, calls
    /// `<name>()`, and reads the result at `<name>_ret_ptr()`. Scalar-only
    /// functions keep taking and returning wasm values.
    pub fn uses_buffers(&self) -> bool {
        matches!(self.ret, Ty::Tensor { .. })
            || self
                .params
                .iter()
                .any(|(_, ty)| matches!(ty, Ty::Tensor { .. }))
    }
}

/// What the host needs in order to call a compiled module.
///
/// It stays host-side in this phase. Embedding it behind `expr_describe()`
/// joins the ABI work in Phase 1, where the vocabulary aligns with the
/// serialized `SystemDescriptor` forms.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Manifest {
    pub functions: Vec<FnSig>,
}

/// A compiled program: a closed module, and the signatures to drive it by.
#[derive(Clone, Debug)]
pub struct Module {
    /// A complete core module. No imports, ever.
    pub wasm: Vec<u8>,
    pub manifest: Manifest,
}

/// Compile a module of annotated `def`s.
///
/// Never panics. Any input that is not a well-typed program in the subset —
/// including a half-typed line, a truncated file, or arbitrary bytes — comes
/// back as [`Diagnostics`] carrying spans.
pub fn compile(source: &str) -> Result<Module, Diagnostics> {
    let (program, manifest) = check::check(source)?;
    let wasm = codegen::emit(&program, &manifest);
    Ok(Module { wasm, manifest })
}

#[cfg(test)]
mod tests;
