//! A typed subset of Python, compiled to closed WebAssembly modules.
//!
//! The premise, from `metor-fsw-2/docs/plans/python-expressions.md`: the panel
//! and the vehicle should run *the same artifact*, an operator should write it
//! in the language they already write `target.py` in, and typing a character
//! into an expression field should not be able to stall anything. That rules
//! out shipping an interpreter as the guest (no static output schema, no
//! closed module, fuel that meters dispatch rather than user work) and it
//! rules out any pipeline with a toolchain in it. What is left is a compiler
//! small enough to live in the flight binary: parse, check, encode.
//!
//! This crate is Phase 0 of that — the compiler spike, no frames and no
//! decorators. What it establishes is the substrate the rest sits on.
//!
//! ## Nothing links at compile time
//!
//! `wasm32-unknown-unknown` is needed to *regenerate* the prelude, never to
//! compile an expression. The prelude — `prelude/`, built by
//! `scripts/regen-prelude.sh` — is checked in as [`PRELUDE`], and compiling
//! means appending functions to those bytes: new types, new bodies, new
//! exports, new data, same memory. [`template`] carries that, including the
//! call-graph walk that drops kernels a program never reaches, so a module
//! that wanted `sin` does not also ship a matmul.
//!
//! Scalar arithmetic never enters the prelude at all. `a * b + c` is native
//! wasm opcodes; the prelude is entered for transcendentals, for tensor
//! kernels, and for nothing else.
//!
//! ## Numerics are nox's, and nox is the oracle
//!
//! The subset's semantics are a tensor library's, not CPython's: ints are
//! `i64` and wrap, `/` is always true division, shapes broadcast by nox's
//! right-aligned rule. Every semantic test therefore runs twice — compiled,
//! under fuel-metered wasmi, and natively against nox in-process — and the
//! results must agree. There is no second interpreter in the loop.
//!
//! The M0 spike qualified that in one place, by measurement. nox's *fixed
//! shape* path (`Tensor<f64, Const<N>, ArrayRepr>`) is correct and well
//! exercised, and it is the oracle. Its *dynamic* shape path is not: an
//! `Array<T, Dyn>` is `Vec`-backed so every operation allocates,
//! `RealField: faer::ComplexField` pulls faer's gemm into the guest, and
//! `DynArray::default` sizes buffers by the sum of the dims instead of their
//! product, so a `Dyn` 3×3 gets six elements. The guest therefore takes
//! `nox_array::ArrayView` — the shape-plus-slice view, which has no
//! dependencies beyond `zerocopy` — and writes its loops out by hand. See the
//! plan's Results section for the numbers behind that.

/// The guest template generated functions are appended to.
///
/// Regenerated by `scripts/regen-prelude.sh`, which is the only thing in this
/// crate that needs a wasm toolchain.
pub const PRELUDE: &[u8] = include_bytes!("prelude.wasm");

pub mod template;

#[cfg(test)]
mod tests;
