//! Compiling a Python module into an ordinary wasm **pack** artifact.
//!
//! The vehicle has one wasm host — the pack ABI — and this module is what
//! lets a compiled program walk through it like any Rust-authored pack: one
//! [`PackEntryDesc`] per `@system`, carrying a full [`SystemDescriptor`]
//! whose vtables are built from the compiled frame layouts, postcard-encoded
//! and baked into the module as a data segment. The pack entry points
//! themselves (`fsw_pack_*`) are generated by [`crate::pack_abi`] as thin
//! adapters over the same static buffers and `<system>_eval` bodies the expr
//! export family drives — one module, two hosts, and the panel's per-sample
//! surface stays untouched.
//!
//! ## Carried ids, and the resolver's second question
//!
//! A binding like `block.plant.sensors.gyro_b` must become an input port
//! whose subset vtable carries the *producer's* component id at the
//! *producer's* record offset — `ComponentId::new` masks the FNV top bit, so
//! re-hashing a name agrees with the real id for only about half of names.
//! [`PackResolver::component_source`] is where those facts come from: the
//! caller reads them out of the producing artifacts' decoded pack manifests
//! and hands them over verbatim; nothing here derives an id it was not given.
//! A `Binding::Produced` (Python reading Python) is the one exception, and
//! not really: its producer's ids are minted *here*, by [`output_port`]'s own
//! convention, so building them again is carrying the minting.
//!
//! ## The run rule is compiled in
//!
//! Pack `execute` runs every cycle and the guest decides (the host driver
//! cannot tell a Python pack from a Rust one). An input-driven system fires
//! when its driving ring's committed position moved, reads the latest of the
//! rest, and skips — `Ok`, publishing nothing — otherwise; an input that has
//! never published skips the cycle. A `rate=` system decimates the cycle
//! clock by the exact `cycle_rate / rate` the divisibility gate proved is an
//! integer, so its firing pattern is deterministic rather than subject to
//! integer-microsecond tick drift.
//!
//! ## Determinism is a contract
//!
//! The host's `entry_identity` is a byte hash over (descriptor,
//! params_schema, reloadable), and reloads compare it; the `.manifest`
//! sidecar is content-hashed too. Everything here therefore iterates in
//! source or first-appearance order — no map ever decides an order — and the
//! compile-twice pin in the tests holds the whole module to byte equality.

use metor_fsw_2_core::abi::{FSW_ABI_VERSION, PackEntryDesc, PackManifest};
use metor_fsw_2_core::log::LogEvent;
use metor_fsw_2_core::{
    Delivery, FanIn, PortConn, PortDesc, PortSchema, SystemDescriptor, SystemKind,
};
use metor_proto::types::{ComponentId, PrimType};
use metor_proto::vtable::builder::{self, FieldBuilder, raw_field, schema};
use metor_proto_wkt::ComponentMetadata;

use crate::manifest::{Binding, Frame, System};
use crate::state::RNG_FIELD;
use crate::{Diagnostics, Manifest, Resolver, Ty, check, codegen};

/// The physical facts behind one bound component, carried from the producing
/// artifact's decoded pack manifest. See the module docs: ids and offsets are
/// handed over, never re-derived.
#[derive(Clone, Debug)]
pub struct ComponentSource {
    /// Producing instance name (unprefixed wiring name).
    pub instance: String,
    /// The producing output port's name.
    pub port_name: String,
    /// The producing port's edge key (`PortId::Component`).
    pub frame_id: ComponentId,
    /// The producing port's worst-case record size.
    pub max_size: usize,
    /// The component's carried unprefixed id.
    pub component_id: ComponentId,
    /// The component's unprefixed name (`sensors.gyro_b`).
    pub component_name: String,
    /// Element type in the producer's record.
    pub prim: PrimType,
    /// Announced dims; empty for a scalar.
    pub shape: Vec<usize>,
    /// Byte offset of the component in the producer's record.
    pub offset: usize,
}

/// What a pack compile asks of its host beyond the type questions of
/// [`Resolver`]: the physical source of every component a binding names.
pub trait PackResolver: Resolver {
    /// The producing port and record placement of the component at `path`.
    /// Must answer for every path [`Resolver::component`] answered.
    fn component_source(&self, path: &str) -> Option<ComponentSource>;
}

/// A compiled pack: the module (both export families), the expr manifest it
/// also bakes, and the `PackManifest` bytes it bakes for `fsw_pack_describe`
/// — the same bytes a `.manifest` sidecar carries.
#[derive(Clone, Debug)]
pub struct PackProgram {
    /// A complete core module speaking both the expr and pack ABIs.
    pub wasm: Vec<u8>,
    /// The expr manifest (also behind `expr_manifest_ptr`).
    pub manifest: Manifest,
    /// Postcard [`PackManifest`] bytes (also behind `fsw_pack_manifest_ptr`).
    pub pack_manifest: Vec<u8>,
}

/// Compile a module of frames and systems into a pack artifact.
///
/// `cycle_rate` is the coordinator clock every `rate=` must divide — the one
/// wiring fact the run rule bakes in. Gate rules beyond the language's own:
/// resample stages are rejected (panel-only for now), `rate=` must divide
/// `cycle_rate` exactly, and a system with neither inputs nor a rate has
/// nothing to fire it.
pub fn compile_pack(
    source: &str,
    resolver: &dyn PackResolver,
    cycle_rate: f64,
) -> Result<PackProgram, Diagnostics> {
    let base: &dyn Resolver = resolver;
    let (program, manifest) = check::check(source, base, check::Entry::Module)?;
    gate(&manifest, cycle_rate)?;

    let mut entries = Vec::with_capacity(manifest.systems.len());
    let mut plans = Vec::with_capacity(manifest.systems.len());
    let mut diags = Diagnostics::default();
    for system in &manifest.systems {
        let Some(groups) = group_bindings(system, &manifest, resolver, &mut diags) else {
            continue;
        };
        entries.push(entry_desc(system, &groups));
        plans.push(entry_plan(system, groups, cycle_rate));
    }
    if !diags.is_empty() {
        return Err(diags);
    }

    let pack_manifest = postcard::to_allocvec(&PackManifest { systems: entries })
        .expect("a pack manifest is postcard-encodable");
    let plan = PackPlan {
        abi_version: FSW_ABI_VERSION,
        manifest: pack_manifest.clone(),
        entries: plans,
    };
    Ok(PackProgram {
        wasm: codegen::emit_with(&program, &manifest, Some(&plan)),
        manifest,
        pack_manifest,
    })
}

/// The pack-gate rules the language itself does not impose.
fn gate(manifest: &Manifest, cycle_rate: f64) -> Result<(), Diagnostics> {
    let mut diags = Diagnostics::default();
    for stage in &manifest.stages {
        diags.push(
            stage.source_span,
            format!("`{}`: resample is panel-only for now", stage.name),
        );
    }
    for system in &manifest.systems {
        match (system.rate, system.inputs.is_empty()) {
            (Some(rate), _) if !divides(rate, cycle_rate) => diags.push(
                system.source,
                format!(
                    "`{}`: rate {rate} Hz does not divide the {cycle_rate} Hz cycle rate",
                    system.name
                ),
            ),
            (None, true) => diags.push(
                system.source,
                format!(
                    "`{}` has no inputs and no `rate=`; nothing would ever fire it",
                    system.name
                ),
            ),
            _ => {}
        }
    }
    if diags.is_empty() { Ok(()) } else { Err(diags) }
}

/// Whether firing every `cycle_rate / rate` cycles hits `rate` exactly.
fn divides(rate: f64, cycle_rate: f64) -> bool {
    if !(rate > 0.0 && rate <= cycle_rate) {
        return false;
    }
    let every = cycle_rate / rate;
    (every - every.round()).abs() < 1e-9 && every.round() >= 1.0
}

// ---------------------------------------------------------------------------
// Grouping bindings into ports
// ---------------------------------------------------------------------------

/// One distinct producing port a system reads: the input [`PortDesc`] under
/// construction plus the unpack plan that fills argument frames from its
/// records.
pub(crate) struct Group {
    port_name: String,
    frame_id: ComponentId,
    max_size: usize,
    fields: Vec<FieldBuilder>,
    metadata: Vec<ComponentMetadata>,
    /// Whether any field of the driving parameter arrives on this port.
    pub(crate) driving: bool,
    /// Shortest record that covers every fill; anything shorter is skipped.
    pub(crate) min_len: u32,
    pub(crate) fills: Vec<Fill>,
}

/// One field's copy out of a producer record into an argument frame slot.
pub(crate) struct Fill {
    /// Which parameter frame (argument buffer index) receives the value.
    pub(crate) param: usize,
    /// Byte offset of the slot within that frame.
    pub(crate) slot_offset: u32,
    /// Byte offset of the source in the producer's record.
    pub(crate) src_offset: u32,
    pub(crate) prim: PrimType,
    pub(crate) elements: u32,
    pub(crate) slot: SlotTy,
}

/// What a frame slot holds: every element is eight bytes, a bool uses the
/// low four.
#[derive(Clone, Copy, PartialEq, Eq)]
pub(crate) enum SlotTy {
    F64,
    I64,
    Bool,
}

/// A frame field's slot shape: element type, announced dims, raw byte length.
fn slot_schema(ty: &Ty) -> (PrimType, Vec<u64>, u32, SlotTy) {
    match ty {
        Ty::F64 => (PrimType::F64, Vec::new(), 8, SlotTy::F64),
        Ty::I64 => (PrimType::I64, Vec::new(), 8, SlotTy::I64),
        Ty::Bool => (PrimType::Bool, Vec::new(), 1, SlotTy::Bool),
        Ty::Tensor { shape, .. } => (
            PrimType::F64,
            shape.iter().map(|&d| d as u64).collect(),
            shape.iter().product::<usize>() as u32 * 8,
            SlotTy::F64,
        ),
    }
}

/// Resolve one system's bindings into producer-port groups, in first-
/// appearance order — the order the descriptor's inputs list and the
/// generated bind walk share with the host's edge synthesis.
fn group_bindings(
    system: &System,
    manifest: &Manifest,
    resolver: &dyn PackResolver,
    diags: &mut Diagnostics,
) -> Option<Vec<Group>> {
    let mut groups: Vec<Group> = Vec::new();
    // Group key: producing (instance, port). A Vec keyed by linear search
    // keeps first-appearance order without a map deciding anything.
    let mut keys: Vec<(String, String)> = Vec::new();
    for (port_idx, port) in system.inputs.iter().enumerate() {
        let driving = system.driving == Some(port_idx);
        for (field, binding) in port.frame.fields.iter().zip(&port.bindings) {
            let source = match binding {
                Binding::Component(path) => match resolver.component_source(path) {
                    Some(source) => source,
                    None => {
                        diags.push(
                            system.source,
                            format!("`{}`: bound component `{path}` vanished", system.name),
                        );
                        return None;
                    }
                },
                Binding::Produced {
                    system: prod,
                    field: prod_field,
                } => produced_source(&manifest.systems[*prod], *prod_field),
                Binding::Resampled { .. } => {
                    unreachable!("the pack gate rejected every stage")
                }
            };
            let key = (source.instance.clone(), source.port_name.clone());
            let at = match keys.iter().position(|k| *k == key) {
                Some(at) => at,
                None => {
                    keys.push(key);
                    groups.push(Group {
                        port_name: source.port_name.clone(),
                        frame_id: source.frame_id,
                        max_size: source.max_size,
                        fields: Vec::new(),
                        metadata: Vec::new(),
                        driving: false,
                        min_len: 0,
                        fills: Vec::new(),
                    });
                    groups.len() - 1
                }
            };
            let group = &mut groups[at];
            group.driving |= driving;
            let elements = source.shape.iter().product::<usize>().max(1) as u32;
            let (_, _, _, slot) = slot_schema(&field.ty);
            group.fills.push(Fill {
                param: port_idx,
                slot_offset: field.offset,
                src_offset: source.offset as u32,
                prim: source.prim,
                elements,
                slot,
            });
            let covered = source.offset as u32 + elements * source.prim.size() as u32;
            group.min_len = group.min_len.max(covered);
            // The subset vtable carries the component exactly as the producer
            // realizes it — carried id, producer offset — so compatibility is
            // the ordinary subset rule and nothing is re-derived.
            if !group
                .metadata
                .iter()
                .any(|m| m.component_id == source.component_id)
            {
                let dims: Vec<u64> = source.shape.iter().map(|&d| d as u64).collect();
                group.fields.push(raw_field(
                    source.offset as u32,
                    elements * source.prim.size() as u32,
                    schema(source.prim, &dims, builder::component(source.component_id)),
                ));
                group.metadata.push(ComponentMetadata {
                    component_id: source.component_id,
                    name: source.component_name.clone(),
                    metadata: Default::default(),
                });
            }
        }
    }
    if groups.len() > 63 {
        diags.push(
            system.source,
            format!("`{}` reads more than 63 distinct ports", system.name),
        );
        return None;
    }
    Some(groups)
}

/// The producer facts behind a `Binding::Produced`: field `field` of an
/// earlier compiled system's output. Its ids follow [`output_port`]'s own
/// minting, so building them here is carrying it, not re-deriving a foreign
/// id.
fn produced_source(producer: &System, field: usize) -> ComponentSource {
    let out = &producer.output;
    let f = &out.fields[field];
    let name = producer.publishes[field].clone();
    let (prim, _, _, _) = slot_schema(&f.ty);
    let shape = match &f.ty {
        Ty::Tensor { shape, .. } => shape.clone(),
        _ => Vec::new(),
    };
    ComponentSource {
        instance: producer.name.clone(),
        port_name: out.name.clone(),
        frame_id: ComponentId::new(&out.name),
        max_size: 8 + out.bytes as usize,
        component_id: ComponentId::new(&name),
        component_name: name,
        prim,
        shape,
        offset: 8 + f.offset as usize,
    }
}

// ---------------------------------------------------------------------------
// Descriptors
// ---------------------------------------------------------------------------

/// The system's one Table output port, built field by field from the compiled
/// frame layout: the record is an 8-byte timestamp then the frame's slots,
/// components named by the manifest's `publishes` (so the anonymous one-field
/// form publishes under the system's own name), so announce and the namespace
/// prefix need nothing new.
fn output_port(frame: &Frame, publishes: &[String]) -> PortDesc {
    let frame_id = ComponentId::new(&frame.name);
    let ts = builder::raw_table(0u32, 8);
    let mut fields: Vec<FieldBuilder> = Vec::with_capacity(frame.fields.len());
    let mut metadata = Vec::with_capacity(frame.fields.len());
    for (field, name) in frame.fields.iter().zip(publishes) {
        let id = ComponentId::new(name);
        let (prim, dims, len, _) = slot_schema(&field.ty);
        fields.push(
            raw_field(
                8 + field.offset,
                len,
                schema(prim, &dims, builder::component(id)),
            )
            .with_timestamp(ts.clone())
            .with_frame(frame_id),
        );
        metadata.push(ComponentMetadata {
            component_id: id,
            name: name.clone(),
            metadata: Default::default(),
        });
    }
    PortDesc {
        name: frame.name.clone(),
        max_size: 8 + frame.bytes as usize,
        schema: PortSchema::Table {
            frame_id,
            vtable: builder::vtable(fields),
            metadata,
        },
        delivery: Delivery::Snapshot,
        fan_in: FanIn::One,
        telemetered: true,
        conn: PortConn::Edge,
    }
}

/// One `@system`'s pack entry: the full descriptor (grouped inputs, the
/// Table output, and the log tail every native entry carries), a unit
/// params schema (the params channel carries only the host-injected `@rng`
/// seed), reloadable.
fn entry_desc(system: &System, groups: &[Group]) -> PackEntryDesc {
    let inputs = groups
        .iter()
        .map(|group| PortDesc {
            name: group.port_name.clone(),
            max_size: group.max_size,
            schema: PortSchema::Table {
                frame_id: group.frame_id,
                vtable: builder::vtable(group.fields.clone()),
                metadata: group.metadata.clone(),
            },
            delivery: Delivery::Snapshot,
            fan_in: FanIn::One,
            telemetered: true,
            conn: PortConn::Edge,
        })
        .collect();
    let outputs = vec![
        output_port(&system.output, &system.publishes),
        PortDesc::msg_named::<LogEvent>("log"),
    ];
    PackEntryDesc {
        descriptor: SystemDescriptor {
            name: system.name.clone(),
            kind: SystemKind::Cyclic,
            inputs,
            outputs,
            capabilities: Vec::new(),
        },
        params_schema: postcard_schema::schema::owned::OwnedNamedType::from(
            <() as postcard_schema::Schema>::SCHEMA,
        ),
        params_docs: Vec::new(),
        reloadable: true,
        params_default: None,
    }
}

// ---------------------------------------------------------------------------
// The plan codegen bakes
// ---------------------------------------------------------------------------

/// Everything the generated pack entry points need, resolved to constants.
pub(crate) struct PackPlan {
    pub(crate) abi_version: u32,
    /// Postcard [`PackManifest`] bytes to bake behind `fsw_pack_manifest_ptr`.
    pub(crate) manifest: Vec<u8>,
    /// Aligned with [`Manifest::systems`].
    pub(crate) entries: Vec<EntryPlan>,
}

/// One entry's generated-code facts.
pub(crate) struct EntryPlan {
    /// The system (and pack entry) name, keying the compiled func.
    pub(crate) name: String,
    pub(crate) groups: Vec<Group>,
    /// `Some(cycles - 1)` for a `rate=` system: the decimation reload value
    /// of the guest's countdown (fire, then skip `cycles - 1` executes).
    pub(crate) rate_reload: Option<i64>,
    /// Index of the `@rng` state slot, for the create-time seed write.
    pub(crate) rng_state: Option<usize>,
    pub(crate) frame_bytes: u32,
    /// Offset of the sample stamp in each argument frame's block.
    pub(crate) arg_stamps: Vec<u32>,
}

fn entry_plan(system: &System, groups: Vec<Group>, cycle_rate: f64) -> EntryPlan {
    EntryPlan {
        name: system.name.clone(),
        arg_stamps: system.inputs.iter().map(|p| p.stamp_offset()).collect(),
        groups,
        rate_reload: system
            .rate
            .map(|rate| (cycle_rate / rate).round() as i64 - 1),
        rng_state: system.state.iter().position(|s| s.name == RNG_FIELD),
        frame_bytes: system.output.bytes,
    }
}
