# @generated by metor pack dev
"""Typed pack module: the systems this pack exports and the records they carry."""

from __future__ import annotations

from pathlib import Path
from typing import Sequence

from metor_config import Item, OutPort, Pack, Record, Sources, System

PACK = Pack(
    id="echo",
    lib="echo_pack",
    libs=str(Path(__file__).resolve().parent / "_libs"),
    abi_version=5,
)


class LogEvent(Record):
    _name = "log"
    _pack = PACK


class Ping(Record):
    _name = "ping"
    _pack = PACK


class SystemStatus(Record):
    _name = "status"
    _pack = PACK


class Echo(System):
    "Copies the newest ping."

    _pack = PACK
    _ty = "echo"
    _outputs = ("output",)

    def __init__(self, *, input: Sources[Ping] = ()) -> None:
        super().__init__({"input": input}, {})

    output: OutPort[Ping]
    log: OutPort[LogEvent]
    status: OutPort[SystemStatus]


class Relay(System):
    "Copies every ping."

    _pack = PACK
    _ty = "relay"
    _outputs = ("output",)

    def __init__(self, *, input: Sources[Ping] = ()) -> None:
        super().__init__({"input": input}, {})

    output: OutPort[Ping]
    log: OutPort[LogEvent]
    status: OutPort[SystemStatus]


class Tap(System):
    "Adds up what every configured port carries."

    _pack = PACK
    _ty = "tap"
    _takes_inputs = True
    _outputs = ("output",)

    def __init__(self, *, items: Sequence[Item] = ()) -> None:
        super().__init__({}, {}, items=items)

    output: OutPort[Ping]
    log: OutPort[LogEvent]
    status: OutPort[SystemStatus]


class Boom(System):
    "Fails on its second cycle."

    _pack = PACK
    _ty = "boom"
    _outputs = ("output",)

    def __init__(self) -> None:
        super().__init__({}, {})

    output: OutPort[Ping]
    log: OutPort[LogEvent]
    status: OutPort[SystemStatus]


class Gain(System):
    "Scales the newest ping."

    _pack = PACK
    _ty = "gain"
    _outputs = ("output",)

    def __init__(self, *, input: Sources[Ping] = (), gain: float) -> None:
        super().__init__({"input": input}, {"gain": gain})

    output: OutPort[Ping]
    log: OutPort[LogEvent]
    status: OutPort[SystemStatus]


class FailInput(System):
    _pack = PACK
    _ty = "fail_input"
    _outputs = ()

    def __init__(self, *, input: Sources[Ping] = ()) -> None:
        super().__init__({"input": input}, {})

    log: OutPort[LogEvent]
    status: OutPort[SystemStatus]


class Retained(System):
    _pack = PACK
    _ty = "retained"
    _outputs = ("output",)

    def __init__(self, *, input: Sources[Ping] = ()) -> None:
        super().__init__({"input": input}, {})

    output: OutPort[Ping]
    log: OutPort[LogEvent]
    status: OutPort[SystemStatus]
