# @generated by metor pack dev
"""Typed pack module: the systems this pack exports and the records they carry."""

from __future__ import annotations

from pathlib import Path

from metor_config import OutPort, Pack, Record, Sources, System

PACK = Pack(
    id="echo",
    lib="echo_pack",
    libs=str(Path(__file__).resolve().parent / "_libs"),
    abi_version=1,
)


class LogEvent(Record): ...


class Ping(Record): ...


class SystemStatus(Record): ...


class Echo(System):
    """Copies the newest ping."""

    _pack = PACK
    _ty = "echo"
    _outputs = ("output",)

    def __init__(self, *, input: Sources[Ping] = ()) -> None:
        super().__init__({"input": input}, {})

    output: OutPort[Ping]
    log: OutPort[LogEvent]
    status: OutPort[SystemStatus]


class Boom(System):
    """Fails on its second cycle."""

    _pack = PACK
    _ty = "boom"
    _outputs = ("output",)

    def __init__(self) -> None:
        super().__init__({}, {})

    output: OutPort[Ping]
    log: OutPort[LogEvent]
    status: OutPort[SystemStatus]


class Gain(System):
    """Scales the newest ping."""

    _pack = PACK
    _ty = "gain"
    _outputs = ("output",)

    def __init__(self, *, input: Sources[Ping] = (), gain: float) -> None:
        super().__init__({"input": input}, {"gain": gain})

    output: OutPort[Ping]
    log: OutPort[LogEvent]
    status: OutPort[SystemStatus]
