[package]
name = "nox"
license = "MIT OR Apache-2.0"
version.workspace = true
edition = "2024"
description = "Array and tensor math with fixed and dynamic dimensions."
repository = "https://github.com/metor-sys/metor"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
std = ["thiserror/std", "faer/std", "nox-array/std"]
serde = ["dep:serde", "smallvec/serde"]

[dependencies]
typenum = "1.20.1"
thiserror = { version = "2.0.20", default-features = false }
seq-macro = "0.3.6"
faer = { version = "0.24.4", default-features = false, features = ["linalg"] }
libm = "0.2.16"
inplace_it = "0.3.6"
smallvec.version = "1.16.0"
smallvec.features = ["const_generics", "union"]
nox-array.path = "./array"

zerocopy.version = "0.8.56"
zerocopy.features = ["derive"]

# debug
approx = "0.5.1"

# serialize
serde.version = "1.0.229"
serde.optional = true
serde.features = ["derive"]
