//! Shared test bootstrap: the pack modules are venv-only build artifacts
//! (normally regenerated by `uv sync`), so a suite that evaluates
//! `target.py` lays them out first — the same `pack dev` payloads the
//! packs' build backends produce, built hermetically so a bare `cargo test`
//! needs no venv. The evaluator finds each pack's `.metor` through the
//! target's `[tool.uv.sources]`.

use std::path::PathBuf;
use std::sync::{Mutex, MutexGuard, OnceLock};

use metor_fsw_2::wiring::{PackDevOptions, pack_dev};

/// Resolving `target.py` binds its `TcpServer` on a fixed port; tests that do
/// so in the same binary take this guard so the parallel threads don't race
/// on the bind. Poisoning is ignored — a panicked holder released the port.
pub fn link_port_guard() -> MutexGuard<'static, ()> {
    static LINK_PORT: Mutex<()> = Mutex::new(());
    LINK_PORT.lock().unwrap_or_else(|e| e.into_inner())
}

/// Lay out both packs' `.metor` payloads, once per test binary; `false`
/// (with a note) if they cannot be built here — callers skip, matching the
/// suite-wide convention.
pub fn ensure_stubs() -> bool {
    static STUBS: OnceLock<bool> = OnceLock::new();
    *STUBS.get_or_init(|| {
        let systems = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("systems");
        for pack in ["adcs-systems", "adcs-sequences"] {
            if let Err(e) = pack_dev(&systems.join(pack), &PackDevOptions::default()) {
                eprintln!("skipping: pack dev layout for {pack} failed: {e}");
                return false;
            }
        }
        true
    })
}

/// Re-link a resolved target's dl systems statically: null every cdylib
/// system's `artifact` (the [`Registry`] factory takes over) and drop
/// process isolation, which needs an artifact to spawn. A wasm-backed
/// system — the target's compiled Python — has no static twin and keeps its
/// artifact.
#[allow(dead_code)] // each test binary compiles its own copy of this module
pub fn link_statically(wiring: &mut metor_fsw_2::Wiring) {
    let wasm_backed: std::collections::HashSet<String> = wiring
        .artifacts
        .iter()
        .filter(|a| a.kind == metor_fsw_2::ir::ArtifactKind::Wasm)
        .map(|a| a.id.clone())
        .collect();
    for spec in &mut wiring.systems {
        if spec
            .artifact
            .as_deref()
            .is_some_and(|id| wasm_backed.contains(id))
        {
            continue;
        }
        spec.artifact = None;
        spec.process = false;
    }
}
