//! Shared test bootstrap: the pack modules are venv-only build artifacts
//! (normally regenerated by `uv sync`), so a suite that evaluates
//! `mission.py` regenerates them first — the same artifacts the build
//! backends produce, built hermetically so a bare `cargo test` needs no
//! venv. Mixed mode, like the mission itself: the mission-level `stubgen`
//! covers the legacy `seqs` artifact, and `pack dev` lays out the `adcs`
//! path-source pack (whose `.metor` the evaluator finds through the
//! mission's `[tool.uv.sources]`).

use std::path::PathBuf;
use std::sync::OnceLock;

use metor_fsw_2::wiring::{PackDevOptions, StubgenOptions, pack_dev, stubgen};

/// Generate the mission's `.metor/packs` and the adcs pack's `.metor`
/// layout, once per test binary; `false` (with a note) if they cannot be
/// built here — callers skip, matching the suite-wide convention.
pub fn ensure_stubs() -> bool {
    static STUBS: OnceLock<bool> = OnceLock::new();
    *STUBS.get_or_init(|| {
        let dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
        let opts = StubgenOptions {
            mission_dir: dir.clone(),
            out_dir: Some(dir.join(".metor").join("packs")),
            check: false,
            build: true,
            release: false,
            cargo_args: Vec::new(),
        };
        if let Err(e) = stubgen(&opts) {
            eprintln!("skipping: stub generation failed: {e}");
            return false;
        }
        let pack = dir.join("systems").join("adcs-systems");
        match pack_dev(&pack, &PackDevOptions::default()) {
            Ok(_) => true,
            Err(e) => {
                eprintln!("skipping: pack dev layout failed: {e}");
                false
            }
        }
    })
}
