//! Shared test bootstrap: the pack stubs are venv-only build artifacts
//! (`.metor/packs`, normally regenerated by `uv sync`), so a suite that
//! evaluates `mission.py` regenerates them first — the same artifact the
//! build backend produces, built hermetically so a bare `cargo test` needs
//! no venv.

use std::path::PathBuf;
use std::sync::OnceLock;

use metor_fsw_2::wiring::{StubgenOptions, stubgen};

/// Generate `.metor/packs` for the example mission, once per test binary;
/// `false` (with a note) if the packs cannot be built here — callers skip,
/// matching the suite-wide convention.
pub fn ensure_stubs() -> bool {
    static STUBS: OnceLock<bool> = OnceLock::new();
    *STUBS.get_or_init(|| {
        let dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
        let opts = StubgenOptions {
            mission_dir: dir.clone(),
            out_dir: Some(dir.join(".metor").join("packs")),
            check: false,
            build: true,
            release: false,
            cargo_args: Vec::new(),
        };
        match stubgen(&opts) {
            Ok(_) => true,
            Err(e) => {
                eprintln!("skipping: stub generation failed: {e}");
                false
            }
        }
    })
}
