//! The typed Python module `pack dev` renders from a pack's descriptor.
//!
//! One `Record` marker class per record name the pack's ports carry, one
//! `System` subclass per entry, and a `@dataclass` per nested params object.
//! The text is deterministic and holds no absolute path: the module locates
//! its own `_libs` at import.

use std::collections::BTreeMap;

use serde_json::Value;

use super::config::PackRef;
use super::pack_dev::PackDevError;
use crate::pack::def::{PackDef, PackSystemDef};
use crate::system::PortDef;

/// The records every system has whatever it declared, named after their Rust types.
const FRAMEWORK: [(&str, &str); 2] = [("log", "LogEvent"), ("status", "SystemStatus")];

/// Renders `<module>/__init__.py` for `def`.
pub fn render(pack: &PackRef, abi_version: u32, def: &PackDef<'_>) -> Result<String, PackDevError> {
    let mut records: Vec<&str> = FRAMEWORK.iter().map(|(name, _)| *name).collect();
    for port in def.systems.iter().flat_map(ports) {
        if !records.contains(&port.record) {
            records.push(port.record);
        }
    }
    records.sort_unstable();

    let schemas: Vec<Value> = def
        .systems
        .iter()
        .map(parse_schema)
        .collect::<Result<_, _>>()?;
    let mut defs = BTreeMap::new();
    for schema in &schemas {
        collect_defs(schema, &mut defs);
    }
    let mut systems = String::new();
    for (system, schema) in def.systems.iter().zip(&schemas) {
        systems.push_str(&entry(system, schema, &defs)?);
    }

    let mut out = header(defs.is_empty());
    out.push_str(&format!(
        "PACK = Pack(\n    id=\"{}\",\n    lib=\"{}\",\n    \
         libs=str(Path(__file__).resolve().parent / \"_libs\"),\n    \
         abi_version={abi_version},\n)\n",
        pack.id, pack.lib
    ));
    for record in records {
        out.push_str(&format!("\n\nclass {}(Record): ...\n", class_of(record)));
    }
    for (name, object) in &defs {
        out.push_str(&dataclass(name, object, &defs));
    }
    out.push_str(&systems);
    Ok(out)
}

/// The module's provenance line and imports.
fn header(no_dataclass: bool) -> String {
    let dataclasses = if no_dataclass {
        ""
    } else {
        "from dataclasses import dataclass\n"
    };
    format!(
        "# @generated by metor pack dev\n\
         \"\"\"Typed pack module: the systems this pack exports and the records they carry.\"\"\"\n\n\
         from __future__ import annotations\n\n\
         {dataclasses}from pathlib import Path\n\n\
         from metor_config import OutPort, Pack, Record, Sources, System\n\n"
    )
}

fn ports<'a>(system: &'a PackSystemDef<'_>) -> impl Iterator<Item = &'a PortDef> {
    system.def.inputs.iter().chain(&system.def.outputs)
}

/// The Python class of a record name: the framework's two, else PascalCase.
fn class_of(record: &str) -> String {
    match FRAMEWORK.iter().find(|(name, _)| *name == record) {
        Some((_, class)) => (*class).to_string(),
        None => pascal(record),
    }
}

fn pascal(name: &str) -> String {
    name.split('_')
        .filter(|part| !part.is_empty())
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
                None => String::new(),
            }
        })
        .collect()
}

/// The params schema as an object, or an empty one for a system without params.
fn parse_schema(system: &PackSystemDef<'_>) -> Result<Value, PackDevError> {
    let Some(raw) = system.params.as_deref() else {
        return Ok(Value::Object(serde_json::Map::new()));
    };
    serde_json::from_str(raw.get()).map_err(|source| PackDevError::Schema {
        system: system.ty.to_string(),
        source,
    })
}

/// Adds every object in the schema's `$defs` to the module's dataclasses.
fn collect_defs(schema: &Value, defs: &mut BTreeMap<String, Value>) {
    let Some(entries) = schema.get("$defs").and_then(Value::as_object) else {
        return;
    };
    for (name, object) in entries {
        if object.get("properties").is_some() {
            defs.insert(name.clone(), object.clone());
        }
    }
}

/// One nested params object as a dataclass of its properties.
fn dataclass(name: &str, object: &Value, defs: &BTreeMap<String, Value>) -> String {
    let mut out = format!("\n\n@dataclass\nclass {name}:\n");
    if let Some(doc) = object.get("description").and_then(Value::as_str) {
        out.push_str(&docstring(doc, "    "));
    }
    let fields = properties(object);
    if fields.is_empty() {
        out.push_str("    pass\n");
    }
    for (field, schema) in fields {
        out.push_str(&format!(
            "    {field}: {}{}\n",
            python_type(&schema, defs),
            default_of(&schema, is_required(object, &field))
        ));
    }
    out
}

/// One system as its `System` subclass.
fn entry(
    system: &PackSystemDef<'_>,
    schema: &Value,
    defs: &BTreeMap<String, Value>,
) -> Result<String, PackDevError> {
    let inputs = &system.def.inputs;
    let params = properties(schema);
    for (name, _) in &params {
        if inputs.iter().any(|port| port.name == *name) {
            return Err(PackDevError::NameClash {
                system: system.ty.to_string(),
                name: name.clone(),
            });
        }
    }
    let mut out = format!("\n\nclass {}(System):\n", pascal(system.ty));
    if !system.doc.is_empty() {
        out.push_str(&docstring(&system.doc, "    "));
        out.push('\n');
    }
    let declared: Vec<&str> = system
        .def
        .outputs
        .iter()
        .map(|port| port.name)
        .filter(|name| !FRAMEWORK.iter().any(|(framework, _)| framework == name))
        .collect();
    out.push_str(&format!(
        "    _pack = PACK\n    _ty = \"{}\"\n    _outputs = {}\n\n",
        system.ty,
        tuple(&declared)
    ));

    let mut signature = String::new();
    for port in inputs {
        signature.push_str(&format!(
            ", {}: Sources[{}] = ()",
            port.name,
            class_of(port.record)
        ));
    }
    for (name, property) in &params {
        signature.push_str(&format!(
            ", {name}: {}{}",
            python_type(property, defs),
            default_of(property, is_required(schema, name))
        ));
    }
    // A bare `*` with nothing after it is a syntax error.
    let keywords = if signature.is_empty() { "" } else { ", *" };
    out.push_str(&format!(
        "    def __init__(self{keywords}{signature}) -> None:\n        \
         super().__init__({{{}}}, {{{}}})\n",
        pairs(inputs.iter().map(|port| port.name)),
        pairs(params.iter().map(|(name, _)| name.as_str()))
    ));
    out.push('\n');
    for port in &system.def.outputs {
        if FRAMEWORK.iter().any(|(name, _)| *name == port.name) {
            continue;
        }
        out.push_str(&format!(
            "    {}: OutPort[{}]\n",
            port.name,
            class_of(port.record)
        ));
    }
    out.push_str("    log: OutPort[LogEvent]\n    status: OutPort[SystemStatus]\n");
    Ok(out)
}

/// `{"a": a, "b": b}`'s body, the dict a generated `__init__` forwards.
fn pairs<'a>(names: impl Iterator<Item = &'a str>) -> String {
    names
        .map(|name| format!("\"{name}\": {name}"))
        .collect::<Vec<_>>()
        .join(", ")
}

/// A Python tuple literal of `names`, with the trailing comma a single needs.
fn tuple(names: &[&str]) -> String {
    match names {
        [] => "()".to_string(),
        [one] => format!("(\"{one}\",)"),
        many => format!(
            "({})",
            many.iter()
                .map(|name| format!("\"{name}\""))
                .collect::<Vec<_>>()
                .join(", ")
        ),
    }
}

/// A schema object's properties, in the order the schema lists them.
fn properties(schema: &Value) -> Vec<(String, Value)> {
    schema
        .get("properties")
        .and_then(Value::as_object)
        .map(|fields| {
            fields
                .iter()
                .map(|(name, schema)| (name.clone(), schema.clone()))
                .collect()
        })
        .unwrap_or_default()
}

fn is_required(schema: &Value, name: &str) -> bool {
    schema
        .get("required")
        .and_then(Value::as_array)
        .is_some_and(|names| names.iter().any(|entry| entry == name))
}

/// The Python annotation for one property's schema.
fn python_type(schema: &Value, defs: &BTreeMap<String, Value>) -> String {
    if let Some(reference) = schema.get("$ref").and_then(Value::as_str) {
        let name = reference.rsplit('/').next().unwrap_or(reference);
        if defs.contains_key(name) {
            return name.to_string();
        }
        return "object".to_string();
    }
    match schema.get("type") {
        Some(Value::String(ty)) => scalar(ty, schema, defs),
        Some(Value::Array(types)) => {
            let names: Vec<String> = types
                .iter()
                .filter_map(Value::as_str)
                .map(|ty| scalar(ty, schema, defs))
                .collect();
            names.join(" | ")
        }
        _ => "object".to_string(),
    }
}

fn scalar(ty: &str, schema: &Value, defs: &BTreeMap<String, Value>) -> String {
    match ty {
        "number" => "float".to_string(),
        "integer" => "int".to_string(),
        "boolean" => "bool".to_string(),
        "string" => "str".to_string(),
        "null" => "None".to_string(),
        "array" => match schema.get("items") {
            Some(items) => format!("list[{}]", python_type(items, defs)),
            None => "list[object]".to_string(),
        },
        _ => "object".to_string(),
    }
}

/// The keyword default: the schema's `default`, or none for a required field.
fn default_of(schema: &Value, required: bool) -> String {
    match schema.get("default") {
        Some(value) => format!(" = {}", literal(value)),
        None if required => String::new(),
        None => " = None".to_string(),
    }
}

/// One JSON value as the Python literal a default is spelled with.
fn literal(value: &Value) -> String {
    match value {
        Value::Null => "None".to_string(),
        Value::Bool(true) => "True".to_string(),
        Value::Bool(false) => "False".to_string(),
        Value::Number(number) => number.to_string(),
        Value::String(text) => format!("\"{}\"", escape(text)),
        Value::Array(items) => format!(
            "[{}]",
            items.iter().map(literal).collect::<Vec<_>>().join(", ")
        ),
        Value::Object(fields) => format!(
            "{{{}}}",
            fields
                .iter()
                .map(|(key, item)| format!("\"{}\": {}", escape(key), literal(item)))
                .collect::<Vec<_>>()
                .join(", ")
        ),
    }
}

fn escape(text: &str) -> String {
    text.replace('\\', "\\\\").replace('"', "\\\"")
}

/// A doc comment as a docstring, indented and with its lines kept.
fn docstring(doc: &str, indent: &str) -> String {
    let body = doc
        .lines()
        .map(|line| line.trim_end())
        .collect::<Vec<_>>()
        .join(&format!("\n{indent}"));
    format!("{indent}\"\"\"{}\"\"\"\n", escape_doc(&body))
}

fn escape_doc(text: &str) -> String {
    text.replace('\\', "\\\\").replace("\"\"\"", "\\\"\\\"\\\"")
}

#[cfg(test)]
mod tests {
    use std::borrow::Cow;

    use metor_proto::types::ComponentId;
    use serde_json::value::RawValue;

    use super::*;
    use crate::system::SystemDef;

    fn port(name: &'static str, record: &'static str) -> PortDef {
        PortDef {
            name,
            record,
            id: ComponentId::new(record),
            max_len: 8,
            alignment: 4,
            depth: 8,
        }
    }

    fn system(
        ty: &'static str,
        inputs: Vec<PortDef>,
        outputs: Vec<PortDef>,
        params: Option<&'static str>,
    ) -> PackSystemDef<'static> {
        PackSystemDef {
            ty,
            def: SystemDef {
                name: ty,
                inputs,
                outputs,
            },
            doc: Cow::Borrowed(""),
            params: params
                .map(|text| Cow::Owned(RawValue::from_string(text.into()).expect("json"))),
        }
    }

    fn rendered(systems: Vec<PackSystemDef<'static>>) -> Result<String, PackDevError> {
        let reference = PackRef {
            id: "test".into(),
            lib: "test_pack".into(),
            libs: "unused".into(),
        };
        render(&reference, 1, &PackDef { systems })
    }

    #[test]
    fn every_param_kind_renders_with_its_default() {
        let schema = r##"{"type":"object","properties":{
            "rate":{"type":"number","default":0.5},
            "count":{"type":"integer","default":3},
            "armed":{"type":"boolean","default":false},
            "mode":{"type":"string","default":"nadir"},
            "gains":{"type":"array","items":{"type":"number"},"default":[1.0,2.0]},
            "limits":{"$ref":"#/$defs/Limits"},
            "slack":{"type":["number","null"]}},
            "required":["limits"],
            "$defs":{"Limits":{"description":"Bounds on the actuator.",
                "type":"object","properties":{"max":{"type":"number","default":1.0}}}}}"##;
        let text = rendered(vec![system(
            "ctrl",
            vec![port("est", "est")],
            vec![port("cmd", "motor_cmd"), port("log", "log")],
            Some(schema),
        )])
        .expect("renders");

        assert!(text.contains("from dataclasses import dataclass\n"));
        assert!(text.contains("@dataclass\nclass Limits:\n    \"\"\"Bounds on the actuator.\"\"\"\n    max: float = 1.0\n"));
        assert!(text.contains("armed: bool = False"));
        assert!(text.contains("mode: str = \"nadir\""));
        assert!(text.contains("gains: list[float] = [1.0, 2.0]"));
        assert!(text.contains("count: int = 3"));
        assert!(
            text.contains("limits: Limits,"),
            "a required param has no default: {text}"
        );
        assert!(text.contains("slack: float | None = None"));
        assert!(text.contains("cmd: OutPort[MotorCmd]"));
        assert!(text.contains("_outputs = (\"cmd\",)"));
    }

    #[test]
    fn a_param_named_like_an_input_is_a_clash() {
        let clash = rendered(vec![system(
            "nav",
            vec![port("gain", "imu")],
            vec![],
            Some(r#"{"type":"object","properties":{"gain":{"type":"number"}}}"#),
        )]);
        let Err(PackDevError::NameClash { system, name }) = clash else {
            panic!("the clash is reported")
        };
        assert_eq!((system.as_str(), name.as_str()), ("nav", "gain"));
    }

    #[test]
    fn a_system_with_no_ports_still_has_the_framework_records() {
        let text = rendered(vec![system("mode", vec![], vec![], None)]).expect("renders");
        assert!(!text.contains("dataclass"));
        assert!(text.contains("class LogEvent(Record): ..."));
        assert!(text.contains("class SystemStatus(Record): ..."));
        assert!(
            text.contains("    def __init__(self) -> None:\n        super().__init__({}, {})\n")
        );
        assert!(text.contains("_outputs = ()"));
        assert!(text.contains("    log: OutPort[LogEvent]\n    status: OutPort[SystemStatus]\n"));
    }
}
