[package]
name = "metor-fsw-ring"
license = "MIT OR Apache-2.0"
version.workspace = true
repository.workspace = true
edition = "2024"
publish = false
description = "Shared-memory ring buffer for metor-fsw-2"
authors = ["sascha@metor.io"]

[lints]
workspace = true

[dependencies]
memmap2 = "0.9"
stellarator = { path = "../../stellarator" }
zerocopy = { version = "0.8.2", features = ["derive"] }

[target.'cfg(any(target_os = "linux", target_os = "macos"))'.dependencies]
libc = "0.2"

[dev-dependencies]
tempfile = "3.13"
