[package]
name = "metor-panel"
version.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
gpui = "*"
metor-db.path = "../db"
metor-proto.path = "../metor-proto"
metor-proto.features = ["std"]
stellarator.path = "../stellarator"

[[example]]
name = "component_text"
path = "examples/component_text.rs"

[[example]]
name = "time_series_plot"
path = "examples/time_series_plot.rs"

[[example]]
name = "component_table"
path = "examples/component_table.rs"
