# @generated by `metor-fsw stubgen` from the `adcs` pack manifest (crate `adcs-systems`).
# Do not edit by hand.
#
# Regenerate after changing the pack's params or ports:
#     metor-fsw stubgen
# Verify the checked-in stubs are current (CI):
#     metor-fsw stubgen --check
"""Typed pack module for artifact `adcs`."""

from __future__ import annotations

from metor_config import Artifact, Frame, InPort, OutPort, System

ARTIFACT = Artifact(
    id="adcs",
    crate="adcs-systems",
    lib="adcs_systems",
    manifest_hash="sha256:22fb4caa2f6dee848b25c63807899d8612af09e51c8fb856eb5c2928e38a2dfc",
)


class TorqueCmd(Frame):
    """Frame marker (checker-only)."""


class MtqCmd(Frame):
    """Frame marker (checker-only)."""


class Sensors(Frame):
    """Frame marker (checker-only)."""


class Gps(Frame):
    """Frame marker (checker-only)."""


class Wheels(Frame):
    """Frame marker (checker-only)."""


class Body(Frame):
    """Frame marker (checker-only)."""


class World(Frame):
    """Frame marker (checker-only)."""


class Disturb(Frame):
    """Frame marker (checker-only)."""


class Health(Frame):
    """Frame marker (checker-only)."""


class Log(Frame):
    """Frame marker (checker-only)."""


class AttitudeEstimate(Frame):
    """Frame marker (checker-only)."""


class ModeCmd(Frame):
    """Frame marker (checker-only)."""


class Plant(System):
    """`Plant` pack entry."""

    def __init__(
        self,
        *,
        init_angle: float,
        init_rate: float,
        meas_sigma: float,
        seed: int,
        disarmed: bool,
        rho: float,
        cd: float,
        area_aero: float,
        cp_offset_b: tuple[float, float, float],
        m_res_b: tuple[float, float, float],
        area_srp: float,
        cr: float,
        mtq_max_dipole: float,
        init_wheel_h: float,
        init_orbit_phase: float,
    ) -> None:
        super().__init__(
            "Plant",
            ARTIFACT,
            init_angle=init_angle,
            init_rate=init_rate,
            meas_sigma=meas_sigma,
            seed=seed,
            disarmed=disarmed,
            rho=rho,
            cd=cd,
            area_aero=area_aero,
            cp_offset_b=cp_offset_b,
            m_res_b=m_res_b,
            area_srp=area_srp,
            cr=cr,
            mtq_max_dipole=mtq_max_dipole,
            init_wheel_h=init_wheel_h,
            init_orbit_phase=init_orbit_phase,
        )

    torque_cmd: InPort[TorqueCmd]  # input, latest-wins, telemetered
    mtq_cmd: InPort[MtqCmd]  # input, latest-wins, telemetered
    sensors: OutPort[Sensors]  # output, latest-wins, telemetered
    gps: OutPort[Gps]  # output, latest-wins, telemetered
    wheels: OutPort[Wheels]  # output, latest-wins, telemetered
    body: OutPort[Body]  # output, latest-wins, telemetered
    world: OutPort[World]  # output, latest-wins, telemetered
    disturb: OutPort[Disturb]  # output, latest-wins, telemetered
    health: OutPort[Health]  # output, latest-wins, telemetered
    log: OutPort[Log]  # output, latest-wins, telemetered


class Nav(System):
    """`Nav` pack entry."""

    def __init__(
        self,
        *,
        meas_sigma: float,
    ) -> None:
        super().__init__(
            "Nav",
            ARTIFACT,
            meas_sigma=meas_sigma,
        )

    sensors: InPort[Sensors]  # input, latest-wins, telemetered
    gps: InPort[Gps]  # input, latest-wins, telemetered
    attitude_estimate: OutPort[AttitudeEstimate]  # output, latest-wins, telemetered
    health: OutPort[Health]  # output, latest-wins, telemetered
    log: OutPort[Log]  # output, latest-wins, telemetered


class Ctrl(System):
    """`Ctrl` pack entry."""

    def __init__(
        self,
        *,
        q_weight: float = 5.0,
        r_weight: float = 8.0,
        k_desat: float = 0.0005,
        k_detumble: float = 0.00005,
    ) -> None:
        super().__init__(
            "Ctrl",
            ARTIFACT,
            q_weight=q_weight,
            r_weight=r_weight,
            k_desat=k_desat,
            k_detumble=k_detumble,
        )

    attitude_estimate: InPort[AttitudeEstimate]  # input, latest-wins, telemetered
    gps: InPort[Gps]  # input, latest-wins, telemetered
    mode_cmd: InPort[ModeCmd]  # input, latest-wins, telemetered
    sensors: InPort[Sensors]  # input, latest-wins, telemetered
    wheels: InPort[Wheels]  # input, latest-wins, telemetered
    torque_cmd: OutPort[TorqueCmd]  # output, latest-wins, telemetered
    mtq_cmd: OutPort[MtqCmd]  # output, latest-wins, telemetered
    health: OutPort[Health]  # output, latest-wins, telemetered
    log: OutPort[Log]  # output, latest-wins, telemetered
