# @generated by `metor-fsw stubgen` from the `seqs` pack manifest (crate `adcs-sequences`).
# Do not edit by hand.
#
# Regenerate after changing the pack's params or ports:
#     metor-fsw stubgen
# Verify the checked-in stubs are current (CI):
#     metor-fsw stubgen --check
"""Typed pack module for artifact `seqs`."""

from __future__ import annotations

from metor_config import Artifact, Frame, System

ARTIFACT = Artifact(
    id="seqs",
    crate="adcs-sequences",
    lib="adcs_sequences",
    manifest_hash="sha256:e966cd494cb3b565f1140fcdf834422e213d41d647a85ed33e046351c82112ed",
)


class AttitudeEstimate(Frame):
    """Frame marker (checker-only)."""


class Gps(Frame):
    """Frame marker (checker-only)."""


class ModeCmd(Frame):
    """Frame marker (checker-only)."""


class Health(Frame):
    """Frame marker (checker-only)."""


class Log(Frame):
    """Frame marker (checker-only)."""


def commissioning(
    *,
    rate_detumble_enter: float,
    rate_detumble_exit: float,
    est_delta_rad: float,
    est_dwell_s: float,
    coarse_err_rad: float,
    coarse_dwell_s: float,
    confirm_dwell_s: float,
    warmup_timeout_s: float,
    detumble_timeout_s: float,
    settle_timeout_s: float,
    confirm_timeout_s: float,
) -> System:
    """Occupant `commissioning` for a `mode`-style slot's allow set.

    Parameters:
        rate_detumble_enter: Enter the detumble phase only above this estimated rate (rad/s). Sized by wheel capture: absorbing 1.0 rad/s loads the worst axis to ≈38% of the momentum limit, so anything slower goes straight to the wheels and the B-cross phase is reserved for genuinely hot tumbles.
        rate_detumble_exit: Leave detumble below this estimated rate (rad/s) — hysteresis against `enter`.
        est_delta_rad: Estimator-settle gate: successive q̂ deltas below this (rad)…
        est_dwell_s: …for this long (s) completes warm-up.
        coarse_err_rad: Coarse-pointing gate: tracking error to the commanded law's target below this (rad)…
        coarse_dwell_s: …for this long (s) advances to fine pointing.
        confirm_dwell_s: Fine pointing confirms (→ `Completed`) after the error holds for this long (s).
        warmup_timeout_s: Per-phase timeouts (s): expiry publishes `ModeCmd::safe` and fails the sequence.
    """
    return System(
        "commissioning",
        ARTIFACT,
        rate_detumble_enter=rate_detumble_enter,
        rate_detumble_exit=rate_detumble_exit,
        est_delta_rad=est_delta_rad,
        est_dwell_s=est_dwell_s,
        coarse_err_rad=coarse_err_rad,
        coarse_dwell_s=coarse_dwell_s,
        confirm_dwell_s=confirm_dwell_s,
        warmup_timeout_s=warmup_timeout_s,
        detumble_timeout_s=detumble_timeout_s,
        settle_timeout_s=settle_timeout_s,
        confirm_timeout_s=confirm_timeout_s,
    )


def safe_mode() -> System:
    """Occupant `safe_mode` for a `mode`-style slot's allow set."""
    return System("safe_mode", ARTIFACT)
