# @generated by `metor-fsw stubgen` from the `seqs` pack manifest (crate `adcs-sequences`).
# Do not edit by hand.
#
# Regenerate after changing the pack's params or ports:
#     metor-fsw stubgen
# Verify the checked-in stubs are current (CI):
#     metor-fsw stubgen --check
"""Typed pack module for artifact `seqs`."""

from __future__ import annotations

from metor_config import Artifact, Frame, System

ARTIFACT = Artifact(
    id="seqs",
    crate="adcs-sequences",
    lib="adcs_sequences",
    manifest_hash="sha256:a182b22f38142ad6a1f15b1959b0e12c1bddb4eb6f40a1b12a18b3242a9c2fd5",
)


class AttitudeEstimate(Frame):
    """Frame marker (checker-only)."""


class Gps(Frame):
    """Frame marker (checker-only)."""


class ModeCmd(Frame):
    """Frame marker (checker-only)."""


class Health(Frame):
    """Frame marker (checker-only)."""


class Log(Frame):
    """Frame marker (checker-only)."""


def commissioning(
    *,
    rate_detumble_enter: float,
    rate_detumble_exit: float,
    est_delta_rad: float,
    est_dwell_s: float,
    coarse_err_rad: float,
    coarse_dwell_s: float,
    confirm_dwell_s: float,
    warmup_timeout_s: float,
    detumble_timeout_s: float,
    settle_timeout_s: float,
    confirm_timeout_s: float,
) -> System:
    """Occupant `commissioning` for a `mode`-style slot's allow set."""
    return System(
        "commissioning",
        ARTIFACT,
        rate_detumble_enter=rate_detumble_enter,
        rate_detumble_exit=rate_detumble_exit,
        est_delta_rad=est_delta_rad,
        est_dwell_s=est_dwell_s,
        coarse_err_rad=coarse_err_rad,
        coarse_dwell_s=coarse_dwell_s,
        confirm_dwell_s=confirm_dwell_s,
        warmup_timeout_s=warmup_timeout_s,
        detumble_timeout_s=detumble_timeout_s,
        settle_timeout_s=settle_timeout_s,
        confirm_timeout_s=confirm_timeout_s,
    )


def safe_mode() -> System:
    """Occupant `safe_mode` for a `mode`-style slot's allow set."""
    return System("safe_mode", ARTIFACT)
