[project]
name = "adcs-fsw2"
version = "0.1.0"
description = "adcs-fsw2 mission config"
requires-python = ">=3.11"
dependencies = ["adcs-pack", "adcs-seqs", "metor-config"]

[tool.uv.sources]
adcs-pack = { path = "systems/adcs-systems", editable = true }
adcs-seqs = { path = "systems/adcs-sequences", editable = true }
metor-config = { path = "../../libs/metor-fsw-2/python/metor-config", editable = true }
